.github/workflows/build.yml
.github/workflows/release.yml
package.json
src/main.ts
src/router.ts
yarn.lock

This PR adds `Datadog`  in Kong Manager oss
https://konghq.atlassian.net/browse/KAG-2068

feat(main): add `Datadog` support

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
package.json
src/App.vue
src/styles/index.ts
yarn.lock

- adds a GitHub star in the navbar, [KAG-2089](https://konghq.atlassian.net/browse/KAG-2089)
- adds issue template
- adds PR template
The templates are based on those of the `kong/kong` repo.
[KAG-2089]: https://konghq.atlassian.net/browse/KAG-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(*): add GitHub star

---

index.html

chore(page-title): change page title to Kong Manager OSS

---

.github/workflows/backport.yml
src/App.vue
src/assets/icon-stardust.svg
src/components/MakeAWish.vue
src/locales/en.json
src/router.ts

This PR adds the `I wish this page would...` footer. Also adds the backport workflow.
[KAG-2110](https://konghq.atlassian.net/browse/KAG-2110)
[KAG-2110]: https://konghq.atlassian.net/browse/KAG-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(*): add MakeAWish footer

---

src/pages/key-sets/Detail.vue
src/pages/keys/Detail.vue
src/pages/keys/Form.vue
src/pages/keys/List.vue
src/router.ts
tests/playwright/commands/switchDetailTab.ts
tests/playwright/specs/key-sets/01-KeySets.spec.ts
tests/playwright/specs/key-sets/02-Keys.spec.ts
tests/playwright/specs/keys/01-Keys.spec.ts
tests/playwright/specs/vaults/01-Vaults.spec.ts

This PR adds the `Keys` tab in the key set detail page.

feat(key-set): add keys tab

---

.github/dependabot.yml

fix(*): token name for dependabot

---

.github/workflows/.reusable_e2e_tests.yml
tests/playwright/commands/clickConfigurationCopy.ts
tests/playwright/pages/consumers.ts
tests/playwright/pages/index.ts
tests/playwright/pages/plugins.ts
tests/playwright/specs/consumers/01-Consumers.spec.ts
tests/playwright/specs/consumers/02-ConsumerCredentials.spec.ts
tests/playwright/specs/consumers/03-ConsumerPlugins.spec.ts

https://konghq.atlassian.net/browse/KAG-2113

feat(consumers): add test cases for consumers

---

.github/workflows/.reusable_e2e_tests.yml
tests/playwright/commands/expectEmptyEntityList.ts
tests/playwright/commands/getPageHeaderAction.ts
tests/playwright/commands/getPropertyValue.ts
tests/playwright/fixtures/certificates.ts
tests/playwright/pages/ca-certificates.ts
tests/playwright/pages/certificates.ts
tests/playwright/specs/ca-certificates/01-CACertificates.spec.ts
tests/playwright/specs/certificates/01-Certificates.spec.ts

Adds test helpers and test cases for `certificates` and `ca-certificates`.
KAG-2121 KAG-2122

test(certs): certificates and ca-certificates

---

.github/workflows/.reusable_e2e_tests.yml
tests/playwright/pages/snis.ts
tests/playwright/specs/consumers/01-Consumers.spec.ts
tests/playwright/specs/consumers/02-ConsumerCredentials.spec.ts
tests/playwright/specs/consumers/03-ConsumerPlugins.spec.ts
tests/playwright/specs/snis/01-SNIs.spec.ts
tests/playwright/specs/snis/02-SNIsFilter.spec.ts

This PR adds test cases for the SNI entity.
[KAG-2120](https://konghq.atlassian.net/browse/KAG-2120)
[KAG-2120]: https://konghq.atlassian.net/browse/KAG-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(snis): add tests

---

.github/workflows/.reusable_e2e_tests.yml
src/components/HeaderBackButton.vue
src/components/HeaderEditButton.vue
tests/playwright/pages/upstreams.ts
tests/playwright/specs/upstreams/01-Upstreams.spec.ts
tests/playwright/specs/upstreams/02-UpstreamTargets.spec.ts
tests/playwright/specs/upstreams/03-UpstreamFilter.spec.ts

Add tests for the Upstream entity.
[KAG-2123](https://konghq.atlassian.net/browse/KAG-2123)
[KAG-2123]: https://konghq.atlassian.net/browse/KAG-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(upstreams): add tests

---

.github/workflows/.reusable_e2e_tests.yml
package.json
src/components/PageHeader.vue
tests/playwright/commands/clearKongResources.ts
tests/playwright/commands/clickHeaderAction.ts
tests/playwright/commands/deleteKongResource.ts
tests/playwright/commands/selectMethods.ts
tests/playwright/pages/services.ts
tests/playwright/specs/services/01-Service.spec.ts
tests/playwright/specs/services/02-ServiceRoutes.spec.ts
tests/playwright/specs/services/03-ServicePlugins.spec.ts
tests/playwright/specs/services/04-Filtering.spec.ts
yarn.lock

test(gateway-services): add tests

---

.github/workflows/.reusable_e2e_tests.yml
tests/playwright/specs/misc/01-EntityListPagination.spec.ts
tests/playwright/specs/misc/02-NotFound.spec.ts
tests/playwright/specs/upstreams/01-Upstreams.spec.ts

Adding misc test cases.
[KAG-2154](https://konghq.atlassian.net/browse/KAG-2154)
[KAG-2154]: https://konghq.atlassian.net/browse/KAG-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(misc): add tests

---

.github/workflows/.reusable_e2e_tests.yml
src/components/EntityForm/EntityForm.vue
tests/playwright/commands/fillEntityForm.ts
tests/playwright/commands/selectService.ts
tests/playwright/pages/routes.ts
tests/playwright/specs/routes/01-Routes.spec.ts
tests/playwright/specs/routes/02-RoutesPlugins.spec.ts

test(routes): add some tests

---

.github/workflows/.reusable_e2e_tests.yml
src/components/PageHeader.vue
src/locales/en.json
src/pages/plugins/Detail.vue
src/pages/plugins/List.vue
src/pages/plugins/PluginCard.vue
tests/playwright/specs/plugins/01-Plugins.spec.ts
tests/playwright/specs/plugins/02-PluginFilter.spec.ts

Adding tests for the Plugin entity.
[KAG-2124](https://konghq.atlassian.net/browse/KAG-2124)
[KAG-2124]: https://konghq.atlassian.net/browse/KAG-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(plugins): add tests

---

src/composables/useListGeneralConfig.ts

fix(entity-list): disable sorting for all entity lists

---

.github/workflows/.reusable_build.yml
.github/workflows/release.yml
package.json
src/main.ts
src/router.ts
yarn.lock

This reverts commit cf72ba5ce7048950f5902b132229413b887ddd00.
We will reland it once the internal task is ready
KAG-2128

Revert "chore(analytics): datadog integration (#21)"

---

src/components/MakeAWish.vue

feat(*): add version in make-wish email title

---

package.json
src/main.ts
src/pages/upstreams/TargetList.vue
src/router.ts
src/services/apiService.ts
src/stores/info.ts
src/stores/types.ts
tests/playwright/specs/upstreams/02-UpstreamTargets.spec.ts
yarn.lock

- Conditionally display/hide _Mark Healthy/Unhealthy_ actions for upstream targets
- Add `pinia` and the info store
FTI-2839

feat(upstream-target): conditional mark health/unhealthy actions [FTI-2839]

---

src/components/KonnectCTA.vue
src/pages/overview/Overview.vue

This PR adds a link to the Konnect preview screenshot.
Fix KAG-2521

feat(overview): add link to the Konnect screenshot

---

src/components/KonnectCTA.vue
src/pages/overview/Overview.vue

feat(overview): add link to the Konnect screenshot (#72)

---

src/composables/useDocsLink.ts
src/pages/ca-certificates/List.vue
src/pages/certificates/List.vue
src/pages/consumers/List.vue
src/pages/key-sets/List.vue
src/pages/keys/List.vue
src/pages/plugins/List.vue
src/pages/routes/List.vue
src/pages/services/List.vue
src/pages/snis/List.vue
src/pages/upstreams/List.vue
src/pages/vaults/List.vue
src/types/entity.ts
src/types/index.ts

chore(*): update entity docs link (#89)

---

src/pages/ca-certificates/List.vue
src/pages/certificates/List.vue
src/pages/overview/Overview.vue
src/pages/plugins/Form.vue
tests/playwright/specs/plugins/01-Plugins.spec.ts

This PR adds a protocols field in plugin forms.
KAG-2576

feat(plugins): add protocols field in plugin form

---

package.json

Bumping the version to `v3.4.1.0`.

chore(package): bump to v3.4.1.0

---

src/components/KonnectCTA.vue
src/pages/overview/Overview.vue
src/stores/types.ts

This PR brings the latest changes from Kong Manager EE:
- https://github.com/Kong/kong-admin/pull/2916
- https://github.com/Kong/kong-admin/pull/2934

fix(*): style, test and text

---

src/App.vue
src/composables/useDetailGeneralConfig.ts
src/pages/vaults/Form.vue
src/styles/typography.scss
tests/playwright/commands/clickConfigurationCopy.ts
tests/playwright/specs/consumers/01-Consumers.spec.ts

feat(*): enable config card format

---

package.json

chore(package): bump version to 3.5.0.0

---

.github/workflows/release.yml

chore(*): update release pipeline trigger branch

---

package.json
tests/playwright/specs/routes/01-Routes.spec.ts
yarn.lock

fix(*): service query endpoint (#115)

---

.ci/Dockerfile.test-image
.ci/docker-compose.yml
.github/actions/select-gateway-image/action.yml
.github/workflows/.reusable_e2e_tests_ee.yml
.github/workflows/.reusable_e2e_tests_oss.yml
.github/workflows/.reusable_test_image.yml
.github/workflows/release.yml
.github/workflows/test.yml

🍒 https://github.com/Kong/kong-admin/pull/3060 (partial)
This pull request adds a reusable action to allow the easy management of default nightly images to be used on different branches.

chore(ci): per-branch default nightly

---

src/composables/useFormGeneralConfig.ts

This PR enables JSON/YAML previews for all entity forms.

feat(*): entity forms JSON/YAML preview

---

.github/workflows/release.yml
package.json

chore(*): bump 3.6.0.0

---

package.json

Resetting version in `package.json` to `0.0.0.0` on `main` branch

chore(package): reset version on main branch

---

.github/workflows/release.yml
package.json

- Bumped to v3.7.0.0
- Updated CI release workflow for v3.7.0.0

chore(*): release v3.7.0.0

---

package.json

chore(*): bump 3.7.0.0-1

---

.github/dependabot.yml
package.json
yarn.lock

Upgrade to Kongponents 9.
KM-265

chore(deps): upgrade to Kongponents 9

---

package.json
tests/playwright/specs/vaults/01-Vaults.spec.ts
yarn.lock

Adopting https://github.com/Kong/public-ui-components/pull/1489
KM-311

feat(vault): vault provider select

---

.github/workflows/release.yml
package.json

- Bumped to v3.7.0.0
- Updated CI release workflow for v3.7.0.0

chore(*): release v3.8.0.0

---

.github/workflows/backport.yml

chore(ci): fix credentials for backport workflow

---

package.json
pnpm-lock.yaml

[KM-461](https://konghq.atlassian.net/browse/KM-461)
[KM-461]: https://konghq.atlassian.net/browse/KM-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): upgrade vue to 3.5

---

package.json
pnpm-lock.yaml

Upgrade monaco-editor and `@kong-ui-public/expressions` version

chore(deps): update monaco-editor version

---

src/config.ts

chore(gui): remove `ADMIN_GUI_URL`

---

.stylelintrc.cjs
package.json
pnpm-lock.yaml
vite.config.ts

Update to `sass@1.8`.
- Switch to `api: 'modern'`
- Switch to `@use`
KM-620

chore(deps): update to sass@1.8

---

package.json

chore(*): bump 3.9.0.0-rc.3

---

package.json

chore(*): bump 3.9.0.0-rc.4

---

src/styles/inputs.scss

Remove unnecessary padding in plugin form UI

chore(plugin): remove unnecessary padding

---

.github/PULL_REQUEST_TEMPLATE.md

chore(*): update PR template

---

package.json
pnpm-lock.yaml

Upgrading vite and related packages. Migration guide can be found here: https://vite.dev/guide/migration.html, and there should be no breaking change for us.
KM-960

chore(*): upgrade vite

---

.github/dependabot.yml

fix(*): dependabot config
