Kong/kong-manager

- tests/playwright/specs/consumers/02-ConsumerCredentials.spec.ts
Clicking "Delete" will not trigger navigate action and will cause flaky. Simply remove the `withNavigation` guard could fix this
> fix(tests): remove an unnecessary `withNavigation` guard

- src/App.vue
This fixes the UI text for `routes` on the sidebar: Route → Routes
> fix(sidebar): ui text 'route' -> 'routes'

- src/pages/NotFound.vue
Fix 404 page title height. This is caused by the latest `@kong-ui-public/app-layout`.
> fix(*): title line height in 404 page

- .github/workflows/.reusable_e2e_tests_ee.yml
- .github/workflows/.reusable_e2e_tests_oss.yml
- .github/workflows/.reusable_test_image.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- tests/playwright/playwright.config.ts
- tests/playwright/specs-ee/plugins/01-Plugins.spec.ts
This PR adds EE feature test pipeline in preparation for the ability to connect to EE instances.
> test(*): add pipeline for EE features

- src/pages/consumers/ConsumerCredentials.vue
- src/pages/overview/Overview.vue
- src/pages/plugins/Select.vue
- src/stores/info.ts
- src/stores/types.ts
Now that we have pinia store all set up, this PR refactors `apiService.get()` to drill data from `infoStore`.
> refactor(*): get info from infoStore

- src/composables/useDocsLink.ts
- src/pages/ca-certificates/List.vue
- src/pages/certificates/List.vue
- src/pages/consumers/List.vue
- src/pages/key-sets/List.vue
- src/pages/keys/List.vue
- src/pages/plugins/List.vue
- src/pages/routes/List.vue
- src/pages/services/List.vue
- src/pages/snis/List.vue
- src/pages/upstreams/List.vue
- src/pages/vaults/List.vue
- src/types/entity.ts
- src/types/index.ts
This PR updates entity docs links to the new spec URLs.
> chore(*): update entity docs link

- .eslintrc.cjs
- src/components/EntityForm/fields.js
- src/pages/plugins/PluginCardSkeleton.vue
- src/pages/plugins/Select.vue
- src/schemas/ArrayCardContainerFields.ts
- src/schemas/MetricFields.ts
- src/schemas/typedefs.ts
- src/styles/form.scss
This PR removes `k-*` classes from native elements in preparation for the next major Kongponent version.
> chore(*): remove `k-*` classes

- src/components/EntityForm/EntityForm.vue
- src/pages/plugins/Form.vue
Fixes a bug where the `proxy-cache` plugin cannot be successfully installed.
Cause: the schema of this plugin includes some fields whose names have dashes in them. Previously we only supported underscores in field names and dashes were treated as indicators for parent/child field.
This PR converts dashes to underscores before passing the schema to `@kong-ui-public/forms` and converts them back to dashes before submitting.
> fix(plugin): field names with dashes

- package.json
- tests/playwright/specs/routes/01-Routes.spec.ts
- yarn.lock
> fix(*): service query endpoint

- src/components/MakeAWish.vue
- src/composables/useDetailGeneralConfig.ts
- src/composables/useDocsLink.ts
- src/composables/useFormGeneralConfig.ts
- src/composables/useGatewayFeatureSupported.ts
- src/composables/useListGeneralConfig.ts
- src/config.ts
- src/pages/overview/Overview.vue
1. Remove the Kong version from `kconfig.js`
2. Retrieve the Kong version from `useInfoStore`.
FTI-5557
> fix(kconfig): remove kong version from kconfig.js

- tests/playwright/specs-ee/plugins/01-Plugins.spec.ts
the gateway edition detection was not functional due to https://github.com/Kong/kong-ee/pull/7290, we have to disable the ee-related tests until https://github.com/Kong/kong/pull/12097 get merged.
> fix: temporary skip ee tests

- src/components/EntityForm/EntityForm.vue
- src/components/EntityForm/NativeEntityForm.vue
- src/components/EntityForm/mixins/FormPage.js
- src/components/EntityForm/mixins/RedirectMixin.js
- src/components/HeaderBackButton.vue
- src/composables/useFormRedirect.ts
- src/composables/useListRedirect.ts
- src/composables/useRedirect.ts
- src/pages/consumers/ConsumerCredentials.vue
- src/pages/plugins/Form.vue
- tests/playwright/specs/services/01-Service.spec.ts
Previously we always wrap the redirect link with `{ path }`, causing query string lost when performing the redirect.
Support for `returnLink` in the URL query are also removed since they are not used anymore
ref: https://github.com/Kong/kong-admin/pull/2941
> fix: redirect `redirect`/`returnLink` with query

- .github/dependabot.yml
- Temporarily disables version upgrades for `@kong/kongponents` as its alpha versions will introduce breaking changes.
- Adds rule for `@playwright/test` in the root directory so its version will stay the same as the one in the `tests/playwright` directory.
> chore(*): update dependabot rules

- .eslintrc.cjs
- package.json
- yarn.lock
import vue sfc with `.vue` extension can help vscode resolving imports
adopted from kong/kong-admin#3014
> chore(eslint): always require vue extension in import statement

- package.json
- yarn.lock
Upgrades `vue` (3.3.4 -> 3.3.13) to address the following error:
1. go to a consumer's credential tab
2. click on any other item in the sidebar
3. an error would occur
https://github.com/Kong/kong-manager/assets/10095631/712fdfaa-c44b-45f8-bbf6-ae6fa9832ce8
This is a vue bug: https://github.com/vuejs/core/issues/6347
> deps(*): upgrade vue

- src/composables/useBaseGeneralConfig.ts
- src/composables/useDocsLink.ts
- src/composables/useGatewayFeatureSupported.ts
- src/composables/useListGeneralConfig.ts
- src/config.ts
- src/pages/consumers/ConsumerCredentials.vue
- src/pages/overview/Overview.vue
- src/stores/info.ts
- src/stores/types.ts
> fix(kconfig): retrieve edtion from info instead of from kconfig.js -FTI-5557

- src/components/MakeAWish.vue
- src/composables/useDetailGeneralConfig.ts
- src/composables/useDocsLink.ts
- src/composables/useFormGeneralConfig.ts
- src/composables/useGatewayFeatureSupported.ts
- src/composables/useListGeneralConfig.ts
- src/config.ts
- src/pages/consumers/ConsumerCredentials.vue
- src/pages/overview/Overview.vue
- src/stores/info.ts
- src/stores/types.ts
cherry-pick :
- https://github.com/Kong/kong-manager/pull/126
> (backport to 3.5.x)fix(kconfig): remove kong version from kconfig.js-FTI-5557

- .github/workflows/.reusable_build.yml
- .github/workflows/.reusable_e2e_tests_ee.yml
- .github/workflows/.reusable_e2e_tests_oss.yml
- .github/workflows/.reusable_test_image.yml
- .github/workflows/release.yml
> chore(*): bump actions artifacts

- src/pages/ca-certificates/Detail.vue
- src/pages/certificates/Detail.vue
- src/pages/consumers/Detail.vue
- src/pages/key-sets/Detail.vue
- src/pages/keys/Detail.vue
- src/pages/plugins/Detail.vue
- src/pages/routes/Detail.vue
- src/pages/services/Detail.vue
- src/pages/upstreams/Detail.vue
- src/pages/vaults/Detail.vue
Entity config cards no longer emit `copy:success` and `copy:error` events.
> chore(*): remove outdated event handlers

- .ci/docker-compose.yml
- .github/actions/select-gateway-image/action.yml
- .github/workflows/.reusable_e2e_tests_oss.yml
- package.json
- src/pages/routes/Form.vue
- src/pages/routes/List.vue
- tests/playwright/commands/fetchKongResource.ts
- tests/playwright/pages/routes.ts
- tests/playwright/specs/routes-expressions/01-Routes.spec.ts
- vite.config.ts
- yarn.lock
- Added support for creating/editing Expressions routes
- Updated the route list to show traditional and expression columns when Kong Gateway's `router_flavor` is configured to `expressions`
- Added test cases and updated CI workflows
KM-20
> feat(routes): support expressions routes [KM-20]

- package.json
- tests/playwright/specs/upstreams/01-Upstreams.spec.ts
- yarn.lock
> feat: bump entities-upstreams-targets and fix upstreams tests

- src/App.vue
Previously, we needed this element to avoid a vue warning. Now with the upgraded vue, we don't need this element anymore.
Reference: https://github.com/vuejs/core/blob/main/changelogs/CHANGELOG-3.4.md#3428-2024-06-14
> fix(*): remove unused teleport target

- src/pages/plugins/Form.vue
- tests/playwright/specs/consumers/03-ConsumerPlugins.spec.ts
- tests/playwright/specs/plugins/01-Plugins.spec.ts
- tests/playwright/specs/routes/02-RoutesPlugins.spec.ts
- tests/playwright/specs/services/03-ServicePlugins.spec.ts
When creating/editing a scoped plugin from plugin list under another scope, hide scoped plugin's scope change field
> feat(plugin-form): hide scoped plugin's scope change

- .vscode/extensions.json
- src/pages/ca-certificates/List.vue
- src/pages/certificates/List.vue
- src/pages/consumers/List.vue
- src/pages/key-sets/List.vue
- src/pages/keys/List.vue
- src/pages/services/List.vue
- src/pages/snis/List.vue
- src/pages/upstreams/List.vue
- src/pages/vaults/List.vue
KM-770
Add proper `cache-identifier` to entity lists.
> fix(*): add proper cache-identifier to all entity lists

- .github/workflows/backport.yml
Replacing `pull_request_target` with `pull_request` for security concerns.
> chore(*): backport trigger

- src/services/apiService.ts
Updated Axios instance initialization to prioritize useAxios().axiosInstance from @kong-ui-public/entities-shared
Adds support  api service withCredentials
> feat(api): api service use axios from @kong-ui-public/entities-shared

- .npmrc
Fix the warning in checking dependabot.yml
```
The property '#/registries/npm/' of type object did not match one or more of the required schemas
```
> chore: remove auth rule in npmrc

- src/pages/plugins/Form.vue
Instead of redirects to `cancelRoute`, go back to previous page when plugin form editing is canceled.
> feat(pluginform): cancel of plugin edit redirects to plugin select

- .github/actions/select-gateway-image/action.yml
Use images from kong-dev, generated by PRs and nightly build
Use docker image from kong-dev, generated by PRs and nightly build.
KM-984
> chore(ci): Using image from kong-dev due to security

- .ci/docker-compose.yml
- .github/workflows/.reusable_e2e_tests.yml
- .github/workflows/test.yml
- package.json
- pnpm-lock.yaml
- src/main.ts
- src/monaco-workers.ts
- tests/playwright/base-test.ts
- tests/playwright/env.d.ts
- tests/playwright/helpers/console.ts
- tsconfig.json
- vite.config.ts
This pull request switches to the more-official way to declare workers for `monaco-editor`
Currently being tested against https://github.com/Kong/kong/pull/14287
FTI-4283
> refactor(*): make build result CSP compliant
